### PR TITLE
Bump golang to v1.21

### PR DESCRIPTION
**Pull request by votdev**
**Problem:**
Go v1.20 is EOL on 06 Feb 2024.

**Solution:**
Bump golang to v1.21.

**Related Issue:**
https://github.com/harvester/harvester/issues/5310

### CODE REVIEW

**Comment by bk201** [comment]
@Vicente-Cheng Will this cause an issue when importing the package from v1.2 components?

**Comment by FrankYang0529** [comment]
> > @Vicente-Cheng Will this cause an issue when importing the package from v1.2 components?
> 
> Hi @bk201, I just created a draft PR in harvester-installer to use the change in this PR. We can see whether CI can pass. If it can, I think it's good to merge this PR. Thanks.
> 
> [harvester/harvester-installer#696](https://github.com/harvester/harvester-installer/pull/696)

It looks like we have a package issue about "slices". Do we want to make a branch in go-common for v1.2?

**Comment by Vicente-Cheng** [comment]
Hi @votdev, I removed the version because we should not need it for test/lint.
Feel free to update any opinions when you get back. Thanks!

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks for the upgrade.

**Review by Vicente-Cheng — APPROVED** [review]

**Comment by FrankYang0529** [comment]
@mergify backport v1.2.x

**Comment by FrankYang0529** [comment]
@mergify backport v1.2.x

**Pull request merged**
